### ISSUE TITLE
Can't control the device from the UI

### ISSUE THREAD

**Issue by egegrsn** [NetrisTV/ws-qvh#1]
Hi, 

Thanks for the great effort you've put. I can successfully connect and reach my device from "http://127.0.0.1:8080/" port and everything works perfectly. 

However, I can't control the device from the UI, its not responding to my mouse clicks and swipes at all. I hope you can help me to figure out this problem.

I have this error popping out in every 2 seconds
`handle_events: error: libusb: interrupted [code -10]`

Thanks in advance!

**Comment by drauggres** [comment]
Hi. Did you finish [WebDriverAgent setup](http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/)?
If you set it up correctly, after you run it for test in Xcode you should see `ServerURLHere->http://[SOME_IP]:8100<-ServerURLHere` in the output.

Can you open DevTools before openning the steam page (copy link, open new tab, open devtools, paste link and hit the enter) and look at the messages in the first websocket connection (one without parameters)? If WDA was successfully started you will see something like this:
<details>
  <summary>Screenshot. </summary>

![wsqvh](https://user-images.githubusercontent.com/7796592/99299431-44204580-285c-11eb-88a9-bb450841bc42.png)

</details>

Otherwise there will be a error code (e.g. code `65` - most likely problem with signing).

**Comment by egegrsn** [comment]
Hi,
I got the `ServerURLHere` output. I think I finished the setup. I am seeing something similar but not same as your Screenshot.

<img width="1049" alt="Screen Shot" src="https://user-images.githubusercontent.com/38487440/99363773-343d4b80-28c6-11eb-9069-965020212bfa.png">

This is from my WDA test:
`2020-11-17 11:08:16.801379+0300 WebDriverAgentRunner-Runner[12853:4096002] Running tests...
Test Suite 'All tests' started at 2020-11-17 11:08:27.392
Test Suite 'WebDriverAgentRunner.xctest' started at 2020-11-17 11:08:27.393
Test Suite 'UITestingUITests' started at 2020-11-17 11:08:27.394
    t =      nans Suite Set Up
2020-11-17 11:08:27.438227+0300 WebDriverAgentRunner-Runner[12853:4096002] [User Defaults] Couldn't write values for keys (
    KeyboardAutocorrection
) in CFPrefsPlistSource<0x280ebe680> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2020-11-17 11:08:27.466950+0300 WebDriverAgentRunner-Runner[12853:4096002] [User Defaults] Couldn't write values for keys (
    KeyboardPrediction
) in CFPrefsPlistSource<0x280ebe680> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2020-11-17 11:08:27.468758+0300 WebDriverAgentRunner-Runner[12853:4096002] [User Defaults] Couldn't write values for keys (
    KeyboardShowPredictionBar
) in CFPrefsPlistSource<0x280ebe680> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
2020-11-17 11:08:27.472377+0300 WebDriverAgentRunner-Runner[12853:4096002] [User Defaults] Couldn't write values for keys (
    DidShowGestureKeyboardIntroduction
) in CFPrefsPlistSource<0x280ebe680> (Domain: com.apple.Preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2020-11-17 11:08:27.475
    t =     0.00s Set Up
2020-11-17 11:08:27.488036+0300 WebDriverAgentRunner-Runner[12853:4096002] Built at Nov 17 2020 10:14:37
2020-11-17 11:08:27.511509+0300 WebDriverAgentRunner-Runner[12853:4096002] ServerURLHere->http://someip:8100<-ServerURLHere
2020-11-17 11:08:27.512519+0300 WebDriverAgentRunner-Runner[12853:4096380] Using singleton test manager`

Also this is the message I got when I execute `./ws-qvh`

`INFO[0000] Starting WebSocket server
INFO[0024] Device '******' USB connection ready, waiting for ping..
INFO[0024] AudioVideo-Stream has started
INFO[0025] command: "run-wda"
2020/11/17 11:03:37 handle_events: error: libusb: interrupted [code -10]
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -project ./WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=**************** -xcconfig ./wda-build.xcconfig

Build settings from configuration file './wda-build.xcconfig':
    CODE_SIGN_IDENTITY = iPhone Developer
    DEVELOPMENT_TEAM = *****************

2020/11/17 11:03:37 handle_events: error: libusb: interrupted [code -10]
2020/11/17 11:03:39 handle_events: error: libusb: interrupted [code -10]
2020/11/17 11:03:39 handle_events: error: libusb: interrupted [code -10]
2020/11/17 11:03:40 handle_events: error: libusb: interrupted [code -10]`


I am missing something but I don't know what.. Thanks for your help again.

**Comment by drauggres** [comment]
> I am seeing something similar but not same as your Screenshot.

You need to select the response (`Binary Message 261 B`) to see its content.

> handle_events: error: libusb: interrupted [code -10]

I don't think that this errors are produced by WDA. Looks like they came from [gousb](https://github.com/google/gousb/blob/cb06b9fb0d36ba48d5b23c0299dbd1b465c3429b/libusb.go#L190-L192).
Did you try to run `quicktime_video_hack` directly? Does it work without these errors?

**Comment by egegrsn** [comment]
I don't know how to run `quicktime_video_hack`, I tried `go run main.go` and it gave me an error which we discussed in an other issue, everything works well besides controlling the device with touch/swipe events from the UI.

**Comment by drauggres** [comment]
You have devtools opened for "device list" page, but it shoud be a "stream page".

> I don't know how to run `quicktime_video_hack`

Run `go build`, then `./quicktime_video_hack`.

**Comment by egegrsn** [comment]
Which one is stream page?

Also qvh is working well, I can see my screen.

**Comment by egegrsn** [comment]
Qvh is working well, also I opened devtools in stream page

this is the console log from stream page: 
`Failed to run WebDriverAgent. Reason: failed, code: 66`

I have a problem with signing probably.

**Comment by drauggres** [comment]
This command is used to start WDA:
https://github.com/NetrisTV/ws-qvh/blob/a9a487ad1da187b0fa40b7888907f3e93d34fc35/wdaStarter.go#L97-L105

You can try to run it from the same terminal where you run `ws-qvh` to see the output. Maybe you can find the reason.

**Comment by egegrsn** [comment]
OK. I solved the issue. Thanks a lot

**Comment by drauggres** [comment]
What was it? In case someone else runs into this.

**Comment by egegrsn** [comment]
WebDriverAgent wasn't in the ws-qvh directory, I put it there, also I opened WBA project in xcode and changed the team to my team.

Also, what can be done to make the response times faster? Additionally, I think when inside an app, clicking coordinates are shifting, so when I click somewhere, its clicking a little bit higher than where I clicked. I am still testing it.

Huge work, thanks.

**Comment by drauggres** [comment]
> Also, what can be done to make the response times faster? 

Unfortunately, nothing. This is how WDA works. And there is no other tools (as far as I know) for remote control (ui testing) for iOS devices.

> Additionally, I think when inside an app, clicking coordinates are shifting, so when I click somewhere, its clicking a little bit higher than where I clicked.

There is a bug in the client's `master` branch (fixed in [`develop`](https://github.com/NetrisTV/ws-scrcpy/commit/bc7a7f406a6a062380010f0810d76fd655f5b6fa)) with scale calculation. But it causes a huge mistake in the coordinates, not a little shifting.
Anyway, if you run into a problems with the client, please open new ticket [here](https://github.com/NetrisTV/ws-scrcpy/issues).

**Comment by egegrsn** [comment]
Thanks!
