### ISSUE TITLE
Device waiting for ping

### ISSUE THREAD

**Issue by donmezburak** [NetrisTV/ws-qvh#2]
Hello,

When I click the phone, console log says:

INFO[0000] Starting WebSocket server                    
INFO[0004] Device '000080xxxx' USB connection ready, waiting for ping.. 
2021/01/14 13:03:19 handle_events: error: libusb: interrupted [code -10]
2021/01/14 13:03:20 handle_events: error: libusb: interrupted [code -10]
2021/01/14 13:03:22 handle_events: error: libusb: interrupted [code -10]

iPhone: XS Pc: Mac mini Catalina 10.15.3

Thanks

**Comment by drauggres** [comment]
Hi.
Sometimes it happens. Usually the following sequence of steps helps:
1. Disconnect/connect the device from usb
2. Run QuickTime, `New Movie Recording`, select your device in `Camera` list (red circle in the middle). Verify that you see your device screen in QT. Close QT.
3. Optionally. Run `quicktime_video_hack`
4. Try ws-qvh again.

In some rare cases you may need to reboot your device.

**Comment by drauggres** [comment]
To reboot device from cli:
`idevicediagnostics -u <udidnumber> restart` [libimobiledevice](https://github.com/libimobiledevice/libimobiledevice)
To cycle power on usb port:
`uhubctl -a 2 -p <portnumber>` [uhubctl](https://github.com/mvp/uhubctl)

**Comment by donmezburak** [comment]
Thank you for quick response. I fixed the problem with resetting device. By the way, I encountered new problem. DeviceAgent-Runner installed successfully but I could not control device. In my Mac-2019 machine with Big Sur, control works but in Mac-mini Catalina I could not control my device. if you want, I can open new issue for this problem.

Thanks

**Comment by drauggres** [comment]
> By the way, I encountered new problem. DeviceAgent-Runner installed successfully but I could not control device. In my Mac-2019 machine with Big Sur, control works but in Mac-mini Catalina I could not control my device.

Make sure that WDA runs properly ([Starting WebDriverAgent](https://github.com/facebookarchive/WebDriverAgent/wiki/Starting-WebDriverAgent)).
It could be caused by newer iOS version on your device than supported by installed Xcode version (e.g. for iOS 14.3 you will need Xcode 12.3) or problems with code signing ([Real Device Setup](http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/?#appium-xcuitest-driver-real-device-setup)).

**Comment by donmezburak** [comment]
I updated Mac iOS version and Xcode version it works. Thanks
